pipeline {
    agent any
        tools {
            maven 'jenkins-maven'
            }
    
    stages {
        stage('Cloning') {
            steps {
                git 'https://github.com/hema-py/jenkins-maven.git'
                echo "Cloning Done"
            }
        }    
        stage('Build') {
            steps {
                sh "mvn clean package -DskipTests=true"
                archive 'target/*.jar'
                echo "Build Done"
            }    
        }
        stage('Test') {
            steps {
                sh 'mvn test'
		echo "Testing Done"    
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
            
        }
        stage('Quality Gate Status Check') {
            steps{
	         withSonarQubeEnv('SonarQube') {
	     sh "mvn sonar:sonar \
	        -D sonar.login=admin \
            -D sonar.password=admin \
            -D sonar.projectKey=Sonar-maven \
            -D sonar.host.url=http://3.17.110.167:9000/"
	     
                 } 
		    }
	    }
        
    }
}
